config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|vi/ do
    root 'static_pages#home'

    get '/help', to: 'static_pages#help'

    resources :users

    get '/signup', to: 'users#new'
    post '/signup', to: 'users#create'

    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save :downcase_email

  validates :name, presence: true, length: { maximum: Settings.length.digit_20 }
  validates :email, presence: true,
                    length: { minimum: Settings.length.digit_10, maximum: Settings.length.digit_255 },
                    format: { with: Settings.VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: Settings.length.digit_6 }, if: :password

  has_secure_password

  private

  def downcase_email
    email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    locale = params[:locale].to_s.strip.to_sym
    I18n.locale = if I18n.available_locales.include?(locale)
                    locale
                  else
                    I18n.default_locale
                  end
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user&.authenticate(params[:session][:password])
      log_in(user)
    else
      flash.now[:danger] = t('.invalid_email_password')
      render(:new)
    end
  end

  def destroy
    log_out if logged_in?

    redirect_to(root_url)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: :show

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = t('.success')
      redirect_to(@user)
    else
      flash.now[:danger] = t('.failed')
      render(:new)
    end
  end

  def show; end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def load_user
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = 'Ruby on Rails tutorial'
    page_title.blank? ? base_title : [page_title, base_title].join(' | ')
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t(".sentence_html", 
        tutorial_link: link_to(t(".tutorial_link"), "https://www.railstutorial.org/"), 
        author_link: link_to(t(".author_link"), "https://www.michaelhartl.com/"))
    %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".about"), "#" %></li>
      <li><%= link_to t(".contact"), "#" %></li>
      <li><%= link_to t(".news"), "https://news.railstutorial.org/" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".logo"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".home"), root_path %></li>
        <li><%= link_to t(".help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t(".user"), user_path(current_user) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
              <%= t ".account" %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <li><%= link_to t(".profile"), current_user, class: "dropdown-item" %></li> 
              <li><%= link_to t(".settings"), "#", class: "dropdown-item" %></li>
              <li class="divider"></li>
              <li><%= link_to t(".log_out"), logout_path, method: :delete, class: "dropdown-item" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".log_in"), login_path %></li>
        <% end %>
        <li><%= link_to t(".english"), locale: "en" %></li>
        <li><%= link_to t(".vietnamese"), locale: "vi" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger"><%= t(".count_error", count: @user.errors.count) %></div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    <ul>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<% provide :title, "Help" %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide :title, "Home" %>
<div class="center jumbotron">
  <h1><%= t ".heading" %></h1>
  <h2><%= t ".content_html", tutorial_link: link_to(t(".tutorial_link"), "https://www.railstutorial.org/") %></h2>
  <%= link_to t(".sign_up"), signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("Folder.jpg", alt: "Rails logo", width: "200px"),
            "https://rubyonrails.org/" %>

app/views/users/new.html.erb
<% provide(:title, t(".title")) %>
<h1><%= t ".title" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render "shared/error_messages" %>
      <%= f.label User.human_attribute_name("name") %>
      <%= f.text_field :name %>
      <%= f.label User.human_attribute_name("email") %>
      <%= f.email_field :email %>
      <%= f.label User.human_attribute_name("password") %>
      <%= f.password_field :password %>
      <%= f.label User.human_attribute_name("password_confirmation") %>
      <%= f.password_field :password_confirmation %>
      <%= f.submit t(".submit"), class: "btn btn-primary" %>
    <% end %> 
  </div>
</div>
  

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %> <%= @user.name %>
      </h1> 
    </section>
  </aside>
</div>